# Generated by Django 5.2 on 2025-04-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_options_remove_product_is_favorite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproductstats',
            options={'ordering': ['-is_favorite', 'product__name']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
